---
version: '3'
services:

# START SERVICE streamsets.base
  streamsets:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.streamsets.base:3.10.1
    environment: ['SDC_JAVA_OPTS=-Xmx${PROCESSOR_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xms${PROCESSOR_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}']
    command: []
    volumes: ['confluent_poc_processor_streamsets_volume:/data']
    ports: []
    networks: [confluent_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          cpus: '${PROCESSOR_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${PROCESSOR_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${PROCESSOR_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${PROCESSOR_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${PROCESSOR_DEPLOY_LABELS}]
# END SERVICE streamsets.base

volumes: {confluent_poc_processor_streamsets_volume: { external: true }}
networks: {confluent_overlay: { external: true }}
