#!/usr/bin/env bash

export CONTECO_LABEL="confluent.poc - ModEco"
export CONTECO_DESCRIPTION="Modeco Confluent POC module."

export CONTECO_TYPE="confluent"
export CONTECO_NAME="poc"
export CONTECO_TAG="v2.0.4"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
