#!/usr/bin/env bash

export CONTECO_LABEL="confluent.poc - ModEco"
export CONTECO_DESCRIPTION="Modeco Confluent POC module."

export CONTECO_TYPE="confluent"
export CONTECO_NAME="poc"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
