---
version: '3'
services:

# START SERVICE filebeat.base
  filebeat:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.filebeat.base:7.1.1
    environment: ['ES_FILEBEAT_FILEPATHS=${INGEST_DATA_ENVIRONMENT_FILEPATHS}','ES_FILEBEAT_OUTPUT_CONSOLE=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONSOLE}','ES_FILEBEAT_OUTPUT_ELASTICSEARCH=${INGEST_DATA_ENVIRONMENT_OUTPUT_ELASTICSEARCH}','ES_FILEBEAT_OUTPUT_KAFKA=${INGEST_DATA_ENVIRONMENT_OUTPUT_KAFKA}','ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_HOSTS}','ES_FILEBEAT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONFIG_ELASTICSEARCH_INDEX}','ES_FILEBEAT_OUTPUT_CONFIG_KIBANA_HOST=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_HOST}','ES_FILEBEAT_OUTPUT_CONFIG_KIBANA_DASHBOARDS=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONFIG_KIBANA_DASHBOARDS}','ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_HOSTS=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_HOSTS}','ES_FILEBEAT_OUTPUT_CONFIG_KAFKA_TOPIC=${INGEST_DATA_ENVIRONMENT_OUTPUT_CONFIG_KAFKA_TOPIC}']
    command: []
    volumes: ['confluent_poc_ingest_data_filebeat_volume:/usr/share/filebeat/data','/etc:/hostfs/etc:ro'${INGEST_DATA_ENVIRONMENT_FILEPATHS_MAPPING}]
    ports: []
    networks: [confluent_overlay]
    deploy:
      mode: ${INGEST_DATA_DEPLOY_MODE}
      resources:
        limits:
          cpus: '${INGEST_DATA_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${INGEST_DATA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${INGEST_DATA_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${INGEST_DATA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      labels: [${INGEST_DATA_DEPLOY_LABELS}]
# END SERVICE filebeat.base

volumes: {confluent_poc_ingest_data_filebeat_volume: { external: true }}
networks: {confluent_overlay: { external: true }}
