#!/usr/bin/env bash


prefix="confluent_$2"


executionplane --silent docker container prune --force

if [[ "confluent_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_ekg_elasticsearch_volume"
			result=$(docker volume ls | grep "confluent_ekg_elasticsearch_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_ekg_grafana_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_ekg_grafana_volume"
			result=$(docker volume ls | grep "confluent_ekg_grafana_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_ingest_data_filebeat_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_ingest_data_filebeat_volume"
			result=$(docker volume ls | grep "confluent_ingest_data_filebeat_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kafka_connect_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kafka_connect_kafka_connect_secrets_volume"
			result=$(docker volume ls | grep "confluent_kafka_connect_kafka_connect_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kafka_connect_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kafka_connect_kafka_connect_connect_secrets_volume"
			result=$(docker volume ls | grep "confluent_kafka_connect_kafka_connect_connect_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kafka_connect_kafka_connect_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kafka_connect_kafka_connect_data_volume"
			result=$(docker volume ls | grep "confluent_kafka_connect_kafka_connect_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kafka_connect_kafka_connect_jars_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kafka_connect_kafka_connect_jars_volume"
			result=$(docker volume ls | grep "confluent_kafka_connect_kafka_connect_jars_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kz_kafka_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kz_kafka_secrets_volume"
			result=$(docker volume ls | grep "confluent_kz_kafka_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kz_kafka_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kz_kafka_data_volume"
			result=$(docker volume ls | grep "confluent_kz_kafka_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kz_zookeeper_secrets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kz_zookeeper_secrets_volume"
			result=$(docker volume ls | grep "confluent_kz_zookeeper_secrets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kz_zookeeper_data_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kz_zookeeper_data_volume"
			result=$(docker volume ls | grep "confluent_kz_zookeeper_data_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_kz_zookeeper_log_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_kz_zookeeper_log_volume"
			result=$(docker volume ls | grep "confluent_kz_zookeeper_log_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_metrics_overlay_metrics_overlay_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_metrics_overlay_metrics_overlay_volume"
			result=$(docker volume ls | grep "confluent_metrics_overlay_metrics_overlay_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
if [[ "confluent_processor_streamsets_volume" == "$prefix"* ]] ; then
		continue="true"
		while [[ "true" == "$continue" ]] ;
		do
			executionplane docker volume rm "confluent_processor_streamsets_volume"
			result=$(docker volume ls | grep "confluent_processor_streamsets_volume")
			if [[ "$result" == "" ]] ; then
				continue="false"
			else
				sleep 3;
			fi
		done;
	fi
	
