#!/usr/bin/env bash


prefix="confluent_$2"

if [[ "confluent_ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_ekg_elasticsearch_volume
	fi
	
if [[ "confluent_ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_ekg_grafana_volume
	fi
	
if [[ "confluent_ingest_data_filebeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_ingest_data_filebeat_volume
	fi
	
if [[ "confluent_kcsz_kafka_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_kafka_secrets_volume
	fi
	
if [[ "confluent_kcsz_kafka_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_kafka_data_volume
	fi
	
if [[ "confluent_kcsz_zookeeper_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_zookeeper_secrets_volume
	fi
	
if [[ "confluent_kcsz_zookeeper_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_zookeeper_data_volume
	fi
	
if [[ "confluent_kcsz_zookeeper_log_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_zookeeper_log_volume
	fi
	
if [[ "confluent_kcsz_kafka_connect_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_kafka_connect_connect_secrets_volume
	fi
	
if [[ "confluent_kcsz_kafka_connect_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_kafka_connect_secrets_volume
	fi
	
if [[ "confluent_kcsz_kafka_connect_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_kafka_connect_data_volume
	fi
	
if [[ "confluent_kcsz_kafka_connect_jars_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_kafka_connect_jars_volume
	fi
	
if [[ "confluent_kcsz_schema_registry_secrets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_kcsz_schema_registry_secrets_volume
	fi
	
if [[ "confluent_metrics_overlay_metrics_overlay_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_metrics_overlay_metrics_overlay_volume
	fi
	
if [[ "confluent_streamsets_streamsets_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create confluent_streamsets_streamsets_volume
	fi
	
